#!/bin/bash -eu
. `dirname $0`/../library/script

# install packages needed for system stage scripts
install axel gdebi-core xmlstarlet # utils
install checkinstall # build
install python-pip # script languages package managers
install cabextract # unarchivers

