#!/bin/bash -eu
. `dirname $0`/../library/script

fheroes2_url=http://citylan.dl.sourceforge.net/project/fheroes2/fheroes2/fheroes2-20120514-linux-r2860.tar.gz
fheroes2_md5=f3fc6218e0f6b74bb9ac36a5a5c98dbb
install_prefix=/usr/local
bin_path=$install_prefix/games/fheroes2
fheroes2_dir=$install_prefix/fheroes2

# install dependencies
install libsdl-{mixer,net}1.2

if [[ ! -x $bin_path ]]; then
  # download and unpack program files
  download $fheroes2_url $fheroes2_md5
  # tar xzf `basename $fheroes2_url`
  sudo tar xzf `basename $fheroes2_url`

  # move program files
  sudo mkdir -p $fheroes2_dir
  sudo mv ./fheroes2/* $fheroes2_dir/

  # create symlink to executable
  sudo ln -s $fheroes2_dir/fheroes2.x86_64 $bin_path
fi

