#!/bin/bash -eu
. `dirname $0`/../library/script

toolchain_url=http://www.treewalker.org/opendingux/opendingux-toolchain.2012-06-16.tar.bz2
toolchain_md5=97adec736b4dc08d0c0930d8400a9e76
toolchain_name=opendingux-toolchain
toolchain_path=/opt/$toolchain_name

if [[ ! -d $toolchain_path ]]; then
  # install required build tools
  install scons # for gambatte
  
  # download and unpack OpenDingux toolchain
  download $toolchain_url $toolchain_md5
  tar xjf `basename $toolchain_url`
  
  # move toolchain to /opt and change owner
  sudo mv $toolchain_name $toolchain_path
  sudo chown -R root:root $toolchain_path
fi

