#!/bin/bash -eu
. `dirname $0`/../library/script

url=http://www.treewalker.org/opendingux/opendingux-toolchain.2012-06-16.tar.bz2
md5=97adec736b4dc08d0c0930d8400a9e76
install_dir=/opt/opendingux-toolchain

if [[ ! -d $install_dir ]]; then
  # download, unpack and move program files
  download $url $md5
  unpack-downloaded $url
  move ./opendingux-toolchain $install_dir
fi

