#!/bin/bash -eu
. `dirname $0`/../library/script

install apt-file

# close Update Notifier window
pkill update-notifier || true

# update apt-file cache if needed
ls /var/cache/apt/apt-file/* &>/dev/null || sudo apt-file update

