#!/bin/bash -eu
. `dirname $0`/../library/script

name=clean-tty
initd_path=/etc/init.d/$name
start_runlevels=2
stop_runlevels="0 6"

# create init.d script for cleaning visible TTYs on boot and shutdown
write-script $initd_path <<EOF
#!/bin/sh
### BEGIN INIT INFO
# Provides:          $name
# Required-Start:
# Required-Stop:
# Default-Start:     $start_runlevels
# Default-Stop:      $stop_runlevels
# Short-Description: Clean visible TTYs on boot and shutdown
### END INIT INFO

for i in 7 8; do printf '\\033c\\033[?25l\\033[30m' > /dev/tty\$i; done

EOF

# update rc.d
sudo update-rc.d $name stop 00 $stop_runlevels . start 99 $start_runlevels .

