#!/bin/bash -eu
. `dirname $0`/../library/script

compton_url=https://github.com/chjj/compton/archive/master.zip
compton_md5=e71c83c11545f2ea4e4a489f22b99d04
build_deps="libx11-dev libxcomposite-dev libxdamage-dev libxrender-dev libxrandr-dev libdbus-1-dev libconfig-dev libdrm-dev libpcre3-dev libgl1-mesa-dev"

if [[ ! -x /usr/bin/compton ]]; then
  # download and extract compton sources
  engine=wget download $compton_url $compton_md5
  unzip -qo master.zip

  # install build time dependencies
  install $build_deps

  pushd compton-master
    # build compton
    make compton

    # comment man related stuff
    filename=Makefile
    pattern="install: \\\$\(BINS\)"
    perl -pe "s/^($pattern) docs$/\1/" -i $filename
    pcregrep -q "^$pattern$" $filename
    pattern="\@install -m644 \\\$\(MANPAGES\) "
    perl -pe "s/^(\s+)($pattern)/\1# \2/" -i $filename
    pcregrep -q "^\s+# $pattern" $filename

    # create package and install
    sudo checkinstall \
      -y \
      --pkgversion=1.0 \
      --requires=libx11-6,libxcomposite1,libxdamage1,libxfixes3,libxext6,libxrender1,libxrandr2,x11-utils,libpcre3,libconfig9,libgl1-mesa-glx,libdbus-1-3
  popd

  # uninstall build time dependencies
  uninstall $build_deps
fi

