#!/bin/bash -eu
. `dirname $0`/../library/script

url=https://gatotray.googlecode.com/files/gatotray.bin64
md5=2b6b3838dfbd1990707533857edafeba
bin_path=/usr/local/bin/gatotray

if [[ ! -x $bin_path ]]; then
  # download, move binary and set permissions
  download $url $md5
  move `basename $url` $bin_path
  sudo chmod +x $bin_path
fi

