#!/bin/bash -eu
. `dirname $0`/../library/script

url=https://github.com/sgtpep/xubuntu-setup/blob/master/vendor/keyfuzz-0.2.tar.gz
md5=dffcc16ffd68988fafe7365f1124517d

if [[ ! -x /usr/local/sbin/keyfuzz ]]; then
  # download and unpack program source
  engine=wget download $url $md5
  unpack-downloaded $url
  
  pushd keyfuzz-*
    # build and install keyfuzz
    ./configure --disable-lynx
    make
    sudo checkinstall -y
  popd
fi

