#!/bin/bash -eu
. `dirname $0`/../library/script

node_packages="
coffee-script
"
modules_dir=/usr/lib/node_modules

# install node.js and npm from PPA
add-ppa chris-lea/node.js
install nodejs

# install node.js packages
for package in $node_packages; do
  [[ ! -d $modules_dir/$package ]] && sudo npm install -g $package || true
done

# remove npm directories from home
sudo rm -rf ~/{.npm,tmp}

