#!/bin/bash -eu
. `dirname $0`/../library/script

url=https://github.com/facebook/phpsh/archive/master.zip
md5=b9f6214141951a9311b0ec27ec14a418

if [[ ! -x /usr/local/bin/phpsh ]]; then
  # download and unpack program sources
  engine=wget download $url $md5
  unpack-downloaded $url

  # build phpsh package and install
  pushd phpsh-master
    sudo checkinstall -y --pkgversion=1.0 python setup.py install
  popd
fi

