#!/bin/bash -eu
. `dirname $0`/../library/script

# install Gnome Keyring Plugin
add-ppa pidgin-gnome-keyring/ppa
install pidgin-gnome-keyring

# plugin for autohiding Buddy List
install pidgin-extprefs

