#!/bin/bash -eu
. `dirname $0`/../library/script

initd_path=/etc/init.d/rc.local.d
start_runlevels="2 3 4 5"

# write init.d script
write-script $initd_path <<EOF
#! /bin/sh
### BEGIN INIT INFO
# Provides:          rc.local.d
# Required-Start:    \$remote_fs \$syslog \$all
# Required-Stop:
# Default-Start:     $start_runlevels
# Default-Stop:
# Short-Description: Run scripts from /etc/rc.local.d if it exist
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
        for path in `ls /etc/rc.local.d/* 2>/dev/null`; do
                [ "\$VERBOSE" != no ] && log_begin_msg "Running local boot script (\$path)"
                ES=\$?
                [ "\$VERBOSE" != no ] && log_end_msg \$ES
        done
        return
}

case "\$1" in
    start)
        do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '\$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: \$0 start|stop" >&2
        exit 3
        ;;
esac

EOF

# update rc.d
sudo update-rc.d rc.local.d start 99 $start_runlevels .

