#!/bin/bash -eu
. `dirname $0`/../library/script

name=rc.local.d
initd_path=/etc/init.d/$name
start_runlevels="2 3 4 5"
watches_path=/etc/rc.local.d/max-user-watches

# create init.d script for running scripts from /etc/rc.local.d directory on boot
write-script $initd_path <<EOF
#! /bin/sh
### BEGIN INIT INFO
# Provides:          $name
# Required-Start:    \$remote_fs \$syslog \$all
# Required-Stop:
# Default-Start:     $start_runlevels
# Default-Stop:
# Short-Description: Run scripts from /etc/$name it exist
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
        for path in \`ls /etc/$name/* 2>/dev/null\`; do
                [ "\$VERBOSE" != no ] && log_begin_msg "Running local boot script (\$path)"
		\$path
                ES=\$?
                [ "\$VERBOSE" != no ] && log_end_msg \$ES
        done
        return
}

case "\$1" in
    start)
        do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '\$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: \$0 start|stop" >&2
        exit 3
        ;;
esac

EOF

# update rc.d
sudo update-rc.d $name start 99 $start_runlevels .

# add rc.local.d script for updating max-user-watches
write-script $watches_path <<EOF
#!/bin/sh
echo 1048576 > /proc/sys/fs/inotify/max_user_watches

EOF

