#!/bin/bash -eu
. `dirname $0`/../library/script

# single packages that do not require any hacks, dependencies, etc.
packages="
wmctrl
xdotool
beep
w3m
kupfer
keepassx
"

for p in `echo $packages`; do install $p; done

