#!/bin/bash -eu
# install single packages that do not require any hacks, dependencies, etc.

. `dirname $0`/../library/script

packages="
# libraries
aspell-ru

# Xorg utils
xxkb
unclutter
wmctrl
xdotool
mesa-utils

# CLI soft
vim
git
htop
ack-grep
exfat-utils
colordiff
inotify-tools
realpath
beep
w3m
aptitude
ncdu
iotop
unison
zram-config
tree
acpi

# GUI soft
dconf-tools
openbox
kupfer
keepassx
qt4-qtconfig
seahorse
gconf-editor
sqlitebrowser
meld
gimp
mysql-workbench
vlc
shutter
rxvt-unicode-256color
lxshortcut
fbreader
comix
fbpanel
"

# strip out comments
packages=`grep -v "^#" <<< "$packages"`

# install packages one by one
for p in `echo $packages`; do install $p; done

