#!/bin/bash -eu
. `dirname $0`/../library/script

skype_url=http://www.skype.com/go/getskype-linux-beta-ubuntu-64
skype_md5=33e2e45e1154efd09b8b0e01430ecd69

if [[ ! -x /usr/bin/skype ]]; then
  # download and install Skype package
  filename=skype.deb
  download $skype_url $skype_md5 $filename
  sudo gdebi -n $filename
fi

