#!/bin/bash -eu
. `dirname $0`/../library/script

sublime_text_url=http://c758482.r82.cf2.rackcdn.com/Sublime\ Text\ 2.0.1\ x64.tar.bz2
sublime_text_md5=bd816d93239a0af9ade257b2a9dcf8d2
install_prefix=/usr/local

if [[ ! -x $install_prefix/bin/subl ]]; then
  # download and unpack program files
  download "$sublime_text_url" $sublime_text_md5
  tar xjf "`basename "$sublime_text_url"`"
  
  # copy move program files and create symlink to executable
  sublime_text_dir=$install_prefix/sublime-text
  sudo mv Sublime\ Text\ 2 $sublime_text_dir
  bin_path=$install_prefix/bin/subl
  sudo ln -s $sublime_text_dir/sublime_text $bin_path
fi

# create .desktop file
write-file /usr/share/applications/sublime-text.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=Sublime Text
Categories=Development;
Icon=$sublime_text_dir/Icon/128x128/sublime_text.png
Exec=$bin_path
StartupNotify=true

EOF

