#!/bin/bash -eu
. `dirname $0`/../library/script

url=http://c758482.r82.cf2.rackcdn.com/Sublime\ Text\ 2.0.1\ x64.tar.bz2
md5=bd816d93239a0af9ade257b2a9dcf8d2
install_prefix=/usr/local
bin_path=$install_prefix/bin/subl
install_dir=$install_prefix/sublime-text

if [[ ! -x $bin_path ]]; then
  # download, unpack, move program files and create symlink to executable
  download "$url" $md5
  unpack-downloaded "$url"
  sudo mv ./Sublime\ Text\ 2/ $install_dir
  sudo ln -s $install_dir/sublime_text $bin_path
fi

# create .desktop file
write-file /usr/share/applications/sublime-text.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=Sublime Text
Comment=Sophisticated Text Editor
Categories=Development;
Icon=$install_dir/Icon/128x128/sublime_text.png
Exec=`basename $bin_path`
StartupNotify=true

EOF

