#!/bin/bash -eu
. `dirname $0`/../library/script

# preinstalled packaged to remove
packages="
thunderbird
ibus ibus-gtk ibus-gtk3
onboard
orage
gnome-sudoku
simple-scan
xchat
"

for p in `echo $packages`; do uninstall $p; done

