#!/bin/bash -eu
. `dirname $0`/../library/script

repository_url=http://download.virtualbox.org/virtualbox/debian
list_path=/etc/apt/sources.list.d/virtualbox.list

if [[ ! -f $list_path ]]; then
  # add repository URL to source list
  write-file $list_path <<EOF
deb $repository_url quantal contrib non-free

EOF
  # import apt key
  wget -q $repository_url/oracle_vbox.asc -O- | sudo apt-key add -
  # update packages from added repository only
  apt-update-list $list_path
fi

# install VirtualBox
install virtualbox-4.2

if ! VBoxManage list extpacks | grep -q "Oracle VM VirtualBox Extension Pack"; then
  # download Oracle VM Extension Pack
  # SOURCE: https://github.com/xdissent/ievms/blob/master/ievms.sh
  version=`VBoxManage -v`
  major_minor_release=${version%%[-_r]*}
  filename=Oracle_VM_VirtualBox_Extension_Pack-${major_minor_release}.vbox-extpack
  url=http://download.virtualbox.org/virtualbox/${major_minor_release}/${filename}
  md5=22518ce5e06c267287f631915681250c
  download $url $md5
  
  # install Oracle VM Extension Pack
  sudo VBoxManage extpack install $filename

  # add user to group
  sudo adduser $USER vboxusers

  # remove autmatically created directory
  rm -rf ~/.VirtualBox
fi

