#!/bin/bash -eu
. `dirname $0`/../library/script

initd_path=/etc/init.d/virtualbox-guest-utils

# install VirtualBox guest packages
install virtualbox-guest-{dkms,utils,x11}

# disable warnings for VirtualBox Guest init.d script
name=log_warning_msg
sudo perl -pe "s/(\s*)($name .+)/\1# \2/" -i $initd_path
[[ `pcregrep -c "\s*# $name .+" $initd_path` == 1 ]]

