#!/bin/bash -eu
. `dirname $0`/../library/script

xcape_url=https://github.com/alols/xcape/archive/master.zip
xcape_md5=eeb2ba971f82d2a13519472d4cbe7d1d
build_deps="libx11-dev libxtst-dev"

if [[ ! -x /usr/bin/xcape ]]; then
  # download and extract xcape sources
  engine=wget download $xcape_url $xcape_md5
  unzip -qo master.zip
  
  # install compile time dependencies
  install pkg-config
  install $build_deps

  pushd xcape-master
    # compile and install xcape
    make
    sudo checkinstall -y --pkgversion=1.0
  popd

  # uninstall compile time dependencies
  uninstall $build_deps
fi

