#!/bin/bash -eu
. `dirname $0`/../library/script

url=https://github.com/alols/xcape/archive/master.zip
md5=eeb2ba971f82d2a13519472d4cbe7d1d
build_deps="libx11-dev libxtst-dev"

if [[ ! -x /usr/bin/xcape ]]; then
  # download and unpack program sources
  engine=wget download $url $md5
  unpack-downloaded $url
  
  # install build time dependencies
  install $build_deps

  pushd xcape-master
    # build and install xcape
    make
    sudo checkinstall -y --pkgversion=1.0
  popd

  # uninstall build time dependencies
  uninstall $build_deps
fi

