#!/bin/bash -eu
. `dirname $0`/../library/script

default_path=/etc/default/keyboard
xkb_options="
grp:alt_shift_toggle
grp_led:caps
misc:typo
lv3:ralt_switch
ctrl:nocaps
"

md5-check $default_path

# change Xkb options
name=XKBOPTIONS
for option in `echo $xkb_options`; do
  IFS=: read key value <<< "$option"
  if pcregrep -q "^$name=\"(|.+,)$key:.+\"$" $default_path; then
    # update existing option
    sudo perl -pe "s/^($name)=\"(|.+,)$key:[^,\"]+(.*)\"$/\1=\"\2$key:$value\3\"/" -i $default_path
  else
    # add new option
    sudo perl -pe "s/^($name)=\"(.+)\"$/\1=\"\2,$option\"/" -i $default_path
  fi
  pcregrep -q "^$name=\"(|.+,)$option(|,.+)\"$" $default_path
done

# reconfigure keyboard-configuration package if config was changed
if md5-changed; then
  sudo dpkg-reconfigure -f noninteractive keyboard-configuration
  setxkbmap
fi

