#!/bin/bash -eu
netrc_path=~/.netrc
gitconfig_path=~/.gitconfig
ssh_dir=~/.ssh
local_dir=~/.local
mysql_password_path=$local_dir/var/mysql-password
src_dir=$local_dir/src
repo_url=https://github.com/sgtpep/xubuntu-setup

if [[ ! -f $netrc_path && ! -d $ssh_dir ]]; then
  # prompt for GitHub auth credentials
  read -p "GitHub email: " github_email
  read -sp "GitHub password: " github_password
  echo

  # create .netrc with GitHub auth credentials
  cat > $netrc_path <<EOF
machine github.com
  login $github_email
  password $github_password

EOF
  chmod 600 $netrc_path
fi

if [[ ! -f $gitconfig_path ]]; then
  # extract email from .netrc
  email=`grep " login " $netrc_path | awk '{ print $2 }'`
  # extract full name from /etc/passwd
  full_name=`cat /etc/passwd | grep "^$USER:" | cut -d: -f5 | cut -d, -f1`

  # create .gitconfig
  cat > $gitconfig_path <<EOF
[core]
  editor = vim
[user]
  email = $email
  name = $full_name

EOF
fi

if [[ ! -f $mysql_password_path ]]; then
  # prompt for MySQL root password
  read -sp "MySQL root password: " mysql_password
  echo

  # store MySQL root password for future usage
  mkdir -p `dirname $mysql_password_path`
  echo "$mysql_password" | sudo tee $mysql_password_path 1>/dev/null
  sudo chmod go-r $mysql_password_path
fi

# install required packages
sudo apt-get install -y vim git

# clone repo to source directory
repo_name=`basename $repo_url`
if [[ ! -d $src_dir/$repo_name ]]; then
  mkdir -p $src_dir
  cd $src_dir
  git clone $repo_url
  echo "Repository $repo_name was cloned to ${src_dir/$HOME/~}/$repo_name"
fi

