#!/bin/bash -eu
. `dirname $0`/../library/script

# tweak gconf settings that are read by Qt apps
gconftool -t bool -s /desktop/gnome/interface/buttons_have_icons true
gconftool -t bool -s /desktop/gnome/interface/menus_have_icons true

